naive attempt at making same changes as prosauer
joergbrech/Modellbildung-und-Simulation pull request #110
Opened 2021-04-14 17:21 UTC by PhiSpel

I don't know what did not work about @prosauer 's attempt. It does work now, though.

This closes #87 and allows to delete #95 

#107 is fine, as [_toc.yml](content/_toc.yml) in /content will be ignored.

2021-04-14 19:51 UTC, joergbrech requested changes
Looks good!  But shouldn't we delete the `_toc.yml` alltogether? 

The problem with the old PR was - if I remember correctly - that we were waiting for a feature of jb, that was not yet part of an official release. We had some problems with jb autocapitalizing all words in the filename: https://github.com/executablebooks/jupyter-book/issues/595.

2021-04-15 06:56 UTC, PhiSpel commented
> Looks good! But shouldn't we delete the `_toc.yml` alltogether?

Yes, we should, but it will not conflict when compiling.

> 
> The problem with the old PR was - if I remember correctly - that we were waiting for a feature of jb, that was not yet part of an official release. We had some problems with jb autocapitalizing all words in the filename: [executablebooks/jupyter-book#595](https://github.com/executablebooks/jupyter-book/issues/595).

When I built it, capitalisation in ToC was perfectly fine.

2021-04-15 07:22 UTC, joergbrech commented
> Yes, we should, but it will not conflict when compiling.

Can you explain what you mean by this?

2021-04-15 07:37 UTC, PhiSpel commented
> > Yes, we should, but it will not conflict when compiling.
> 
> Can you explain what you mean by this?

`content/_toc.yml` is overwritten when building ToC via `jupyter-book toc content/`
So, it is obsolete and should be deleted (and not added when merging #107 ), but it will not cause conflicts.

2021-04-15 07:45 UTC, joergbrech commented
Ah I get it. Don't worry about conflicts, we should take care of them where they come up, and the conflict with #107 will be resolved once the corresponding branch will be rebased on the new master. Removing the `_toc.yml` file is part of the task associated to this issue and not #106, and the history will be clearer. So could you please remove it?

2021-04-15 07:50 UTC, joergbrech commented on CONTRIBUTING.md
>   * Create new Markdown files or jupyter notebooks or edit the ones that are already there. Check the [wiki](https://github.com/joergbrech/Modellbildung-und-Simulation/wiki) for writing conventions *(
One more thing: Can we mention the naming conventions for file names here? Just a short summary on how the toc is generated from the file names as described in the jupyter book documentation, or maybe even better: A link to the jupyter book documentation

2021-04-15 08:26 UTC, joergbrech commented on CONTRIBUTING.md
>   * Create new Markdown files or jupyter notebooks or edit the ones that are already there. Check the [wiki](https://github.com/joergbrech/Modellbildung-und-Simulation/wiki) for writing conventions *(
Ah, I see that you mention that the toc is based on the file names a few lines further down. I suppose that is enough. Sorry for the noise!

2021-04-15 08:26 UTC, joergbrech approved these changes

2021-04-15 08:27 UTC, merged

2021-04-15 08:27 UTC, joergbrech commented
Thanks!

2021-04-15 08:29 UTC, PhiSpel commented on CONTRIBUTING.md
>   * Create new Markdown files or jupyter notebooks or edit the ones that are already there. Check the [wiki](https://github.com/joergbrech/Modellbildung-und-Simulation/wiki) for writing conventions *(
I added the conventions to the Wiki

2021-04-15 09:41 UTC, PhiSpel commented
The order in ToC seems to be messed up with a concept:

- The order is correct for chapters 0,1,6-11
- The order is alphabetical according to titles and inserted after 11 for chapters 2-5

I don't know, what makes this difference.

2021-04-15 09:46 UTC, joergbrech commented
Also it's fine on `master`. So it's specific to the Continuous Integration run *and* the branch associated with #107.

2021-04-15 09:49 UTC, PhiSpel commented
It actually does work on my local engine..