[WIP] standardized implementation of images
joergbrech/Modellbildung-und-Simulation pull request #113
Opened 2021-04-16 14:49 UTC by sandro-elsweijer

After reworking the introduction I thought it would be a good idea to adapt all images to the new format. Can be merged after #111

2021-04-16 15:17 UTC, joergbrech commented
Thanks! I hate to be pedantic, but would you mind opening an issue associated to this change? I like issue-PR pairs to document the progress of the page and to understand later on why things were changed.

2021-04-17 11:45 UTC, sandro-elsweijer commented
Closes  #114

2021-04-19 11:29 UTC, joergbrech commented
This looks good, but I noticed that the TOC order is messed up again. We should hold of merging this until we figure out what is going on, see also #107 and #110.

2021-04-19 15:27 UTC, joergbrech commented
@sandro-elsweijer, could you please rebase on/merge master? I want to see if the issue with the wrong order of chapters is resolved now that I merged #107.

2021-04-19 16:59 UTC, sandro-elsweijer commented
> @sandro-elsweijer, could you please rebase on/merge master? I want to see if the issue with the wrong order of chapters is resolved now that I merged #107.

After merging the master branch the chapter seem to remain in the wrong order, at least on my local machine.

2021-04-19 18:08 UTC, joergbrech commented
> > @sandro-elsweijer, could you please rebase on/merge master? I want to see if the issue with the wrong order of chapters is resolved now that I merged #107.
> 
> After merging the master branch the chapter seem to remain in the wrong order, at least on my local machine.


They look good in CI: https://998-168147770-gh.circle-artifacts.com/0/html/index.html. Or am I missing something?

2021-04-19 18:14 UTC, sandro-elsweijer commented
> 
> 
> > > @sandro-elsweijer, could you please rebase on/merge master? I want to see if the issue with the wrong order of chapters is resolved now that I merged #107.
> > 
> > 
> > After merging the master branch the chapter seem to remain in the wrong order, at least on my local machine.
> 
> They look good in CI: https://998-168147770-gh.circle-artifacts.com/0/html/index.html. Or am I missing something?

I do not know why they have a wrong order on my local machine, but I can work with that. When the order is right in the CI, the order will probably be right on the website.

2021-04-19 18:32 UTC, joergbrech commented
Ok, I am not super happy that the toc autocreation is so flaky. But then let's keep it for now and just be super diligent and double check the toc order in every PR.

2021-04-19 18:56 UTC, joergbrech requested changes
The image on this page is missing: https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/content/11_pde/01_konvektion_und_diffusion.ipynb

2021-04-19 18:56 UTC, joergbrech commented on content/00_einleitung/03_exercises/02_fluessigkeit_im_boden.ipynb
> +"```{image} images/fluessigkeit.png\n",
This one doesn't get rendered correctly: https://998-168147770-gh.circle-artifacts.com/0/html/00_einleitung/03_exercises/02_fluessigkeit_im_boden.html

2021-04-19 20:05 UTC, sandro-elsweijer commented
> The image on this page is missing: https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/content/11_pde/01_konvektion_und_diffusion.ipynb

Do you mean that I missed this image in my standardization process or is there a second image in this chapter I cannot find?
If the first thing is the case I missed it, but I have changed it now.

2021-04-19 20:35 UTC, joergbrech commented
LGTM! Thanks

2021-04-19 20:35 UTC, joergbrech approved these changes

2021-04-19 20:35 UTC, merged