added additional links to ODE stability
joergbrech/Modellbildung-und-Simulation pull request #126
Opened 2021-05-06 06:35 UTC by PhiSpel

added three links from MATHWORKS

2021-05-06 18:46 UTC, joergbrech requested changes

2021-05-06 18:46 UTC, joergbrech commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "## Zusatzinformationen\n",
Could you make this an admonition? This fits better with the style of the book: https://jupyterbook.org/content/content-blocks.html#notes-warnings-and-other-admonitions

2021-05-07 09:02 UTC, PhiSpel commented
I did this also for Raketenstart, which I used as a template for the Zusatzinformationen

Strangely, it's formatted yellow and I do not know how to globally change the format for `:class: tip`

2021-05-12 11:17 UTC, sandro-elsweijer requested changes
Looks good to me, we can merge it after implementing the hyperlinks

2021-05-12 11:17 UTC, sandro-elsweijer commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "- https://de.mathworks.com/help/matlab/math/choose-an-ode-solver.html\n",
We should stick to using hyperlinks like in the rocket launch information box

2021-05-12 11:59 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "- https://de.mathworks.com/help/matlab/math/choose-an-ode-solver.html\n",
Oh yes, good point

2021-05-12 12:01 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "## Zusatzinformationen\n",
Done in commit ec16ded

2021-05-12 12:03 UTC, sandro-elsweijer approved these changes

2021-05-12 12:05 UTC, merged