Update contributing.md
joergbrech/Modellbildung-und-Simulation pull request #134
Opened 2021-05-14 16:16 UTC by sandro-elsweijer

Closes #132

2021-05-14 16:25 UTC, PhiSpel requested changes
Looks nice, only very few optional thins :)

2021-05-14 16:25 UTC, PhiSpel commented on CONTRIBUTING.md
> +<div style="text-align: right"><a href="https://commons.wikimedia.org/wiki/File:Aedes_Albopictus.jpg" > James Gathany/CDC, Public domain, via Wikimedia Commons </a></div>
Looks good! Do you maybe want to add previews to the formats?

2021-05-14 16:25 UTC, PhiSpel commented on CONTRIBUTING.md
> +````
see above

2021-05-14 16:25 UTC, PhiSpel commented on CONTRIBUTING.md
> +:width: 1200px
most images are 800px wide, maybe change this to make c&p easier

2021-05-14 16:25 UTC, PhiSpel commented on CONTRIBUTING.md
> +```{image} path/to/image.png
most images are in a `image/...` folder, maybe change this to make c&p easier

2021-06-09 10:23 UTC, sandro-elsweijer commented on CONTRIBUTING.md
> +<div style="text-align: right"><a href="https://commons.wikimedia.org/wiki/File:Aedes_Albopictus.jpg" > James Gathany/CDC, Public domain, via Wikimedia Commons </a></div>
This syntax is jupyter/sphinx specific, because of that it won't work in our markdown file. I think it would be helpful, but I fear it is not possible.

2021-06-09 10:23 UTC, sandro-elsweijer commented on CONTRIBUTING.md
> +````
see above

2021-06-09 10:26 UTC, sandro-elsweijer commented on CONTRIBUTING.md
> +:width: 1200px
see b845bca

2021-06-09 10:26 UTC, sandro-elsweijer commented on CONTRIBUTING.md
> +```{image} path/to/image.png
see b845bca

2021-06-09 13:50 UTC, PhiSpel approved these changes
looks good

2021-06-09 13:50 UTC, merged