Phil spel highline pde
joergbrech/Modellbildung-und-Simulation pull request #140
Opened 2021-06-04 13:32 UTC by PhiSpel

- [ ] Should finite differences be introduced elsewhere?
- [ ] Does Gerd agree with this way of including the exercise?

closes #123

2021-06-04 14:47 UTC, sandro-elsweijer requested changes
This should be the introduction to PDEs and because of that you should mention the difference between ODEs and PDEs at least in one sentence. Apart from that, this looks great.

2021-06-04 14:47 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Auch wenn es nicht so aussah, beinhaltet bereits die die Kräftebilanzierung aus [](content:references:highline_static) eine partielle Differentialgleichung. Für einen allgemeinen Massepunkt mit
The formatting of these equations seems weird.

2021-06-04 14:47 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Um diese PDE in ein System von ODEs zu überführen, muss ein sogenannter Differenzenstern für die Ortsableitungen gebildet werden. Im Eindimensionalen ist der Differenzenstern sehr einfach als ze
The last sentence is hard to read.

2021-06-04 14:47 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "$$\\frac{\\partial^2 z}{\\partial x^2} \\approx \\frac{z(x-h)-2z(x)+z(x+h)}{h^2} \\to \\frac{\\partial z_i}{\\partial x^2} = \\frac{z_{i-1}-2z_i+z_{i+1}}{dx^2}.$$\n",
I would start for the difference quotient for the first derivative and build the difference quotient for the second derivative from this. This way it gets clear where the 2z(x) comes from.

2021-06-04 14:47 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Achtung: Für den ersten und den letzten Massenpunkt ($i=1$ und $i=N$) sind zusätzlich die Geschwindigkeit und Verschiebung der Massenpunkte an den Rändern für die finiten Differenzen notwendig.
One "entsteht" too much

2021-06-04 14:47 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Daher müssen Randbedingungen festgelegt werden. Diese ist für die Highline ganz logisch und einfach festzulegen: Die  Geschwindigkeit und Verschiebung der äußeren Elemente sind natürlich $\\math
Maybe we could insert a comment that this type of boundary condition is a Dirichlet boundary condition and that there is also a different type of BC, the Neumann BC, which sets the spacial derivative for this knot.

2021-06-04 14:47 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Diese Lösungsstrategie nennt sich übrigens **Finite-Differenzen-Verfahren** (FDM):\n",
Better Finite-Differenzen-Methode, if you want to use the acronym FDM

2021-06-04 14:47 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Die Ableitungen in der DGL werden durch finite Differenzenquotienten ersetzt. Zusammen mit den Randbedingungen ergibt sich ein lineares (oder auch nichtlineares) Gleichungssystem.\n",
PDE not DGL, and only the spacial derivatives get exchanged. After that you have a system of ODEs and not a linear or non-linear system of algebraic equations.

2021-06-07 09:28 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Die Ableitungen in der DGL werden durch finite Differenzenquotienten ersetzt. Zusammen mit den Randbedingungen ergibt sich ein lineares (oder auch nichtlineares) Gleichungssystem.\n",
see 42db10e

2021-06-07 09:28 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Diese Lösungsstrategie nennt sich übrigens **Finite-Differenzen-Verfahren** (FDM):\n",
see 42db10e

2021-06-07 09:28 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Daher müssen Randbedingungen festgelegt werden. Diese ist für die Highline ganz logisch und einfach festzulegen: Die  Geschwindigkeit und Verschiebung der äußeren Elemente sind natürlich $\\math
see 42db10e

2021-06-07 09:28 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Achtung: Für den ersten und den letzten Massenpunkt ($i=1$ und $i=N$) sind zusätzlich die Geschwindigkeit und Verschiebung der Massenpunkte an den Rändern für die finiten Differenzen notwendig.
see 42db10e

2021-06-07 09:28 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "$$\\frac{\\partial^2 z}{\\partial x^2} \\approx \\frac{z(x-h)-2z(x)+z(x+h)}{h^2} \\to \\frac{\\partial z_i}{\\partial x^2} = \\frac{z_{i-1}-2z_i+z_{i+1}}{dx^2}.$$\n",
see 42db10e

2021-06-07 09:28 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Um diese PDE in ein System von ODEs zu überführen, muss ein sogenannter Differenzenstern für die Ortsableitungen gebildet werden. Im Eindimensionalen ist der Differenzenstern sehr einfach als ze
see 42db10e

2021-06-07 09:28 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "Auch wenn es nicht so aussah, beinhaltet bereits die die Kräftebilanzierung aus [](content:references:highline_static) eine partielle Differentialgleichung. Für einen allgemeinen Massepunkt mit
I wanted to introduce both the parial/partial x convention as well as the z_x convention. I changed the equations in the text to z_x convention, see 42db10e

2021-06-07 09:28 UTC, PhiSpel commented
> This should be the introduction to PDEs and because of that you should mention the difference between ODEs and PDEs at least in one sentence. Apart from that, this looks great.

Thank you for the helpful comments! Now, everything should be in order

2021-06-09 10:17 UTC, sandro-elsweijer approved these changes

2021-06-09 10:18 UTC, merged