Phil spel highline pde improvements
joergbrech/Modellbildung-und-Simulation pull request #143
Opened 2021-06-11 13:22 UTC by PhiSpel

- [ ] get Gerd to look over it

closes #142

2021-06-15 06:16 UTC, PhiSpel commented
940d639 solves #138

2021-06-23 09:11 UTC, sandro-elsweijer requested changes

2021-06-23 09:11 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "$$\\rho \\mathbf{z}_{tt} = k_{ges} \\mathbf{z}_{xx} + d_{ges} {\\mathbf{z}_t}_{xx} + \\mathbf{F}_{\\text{ext}}(t).$$\n",
If we replace m with rho we need to also replace k and d, so that our units are consistent. There must be a spring constant relative to the length and also a relative dampening constant

2021-06-23 09:11 UTC, sandro-elsweijer commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> -    "$$\\frac{\\partial^2 z}{\\partial x^2} \\approx \\frac{z(x-h)-2z(x)+z(x+h)}{h^2} \\to \\frac{\\partial^2 z_i}{\\partial x^2} = \\frac{z_{i-1}-2z_i+z_{i+1}}{dx^2}.$$\n",
Didn't we explain the difference quotient of the first derivative first, and then generated the second one from that?

2021-06-23 09:42 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> -    "$$\\frac{\\partial^2 z}{\\partial x^2} \\approx \\frac{z(x-h)-2z(x)+z(x+h)}{h^2} \\to \\frac{\\partial^2 z_i}{\\partial x^2} = \\frac{z_{i-1}-2z_i+z_{i+1}}{dx^2}.$$\n",
Yes, Gerd thought that it was not necessary, though.
Somehow, it makes sense to state the second derivative straight away, so the explanation is more lean. Either way, for more detailed understanding of difference quotient a separate overview would be preferable. I suggested this in #123, but forgot to trace it, oups. I'll open a separate issue to be sure.

2021-06-23 09:47 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "$$\\rho \\mathbf{z}_{tt} = k_{ges} \\mathbf{z}_{xx} + d_{ges} {\\mathbf{z}_t}_{xx} + \\mathbf{F}_{\\text{ext}}(t).$$\n",
As $k_ges := k dx$ I thought this was not necessary. Let's quickly chat later, I can also add some admonition.

2021-07-01 04:54 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> +    "$$\\rho \\mathbf{z}_{tt} = k_{ges} \\mathbf{z}_{xx} + d_{ges} {\\mathbf{z}_t}_{xx} + \\mathbf{F}_{\\text{ext}}(t).$$\n",
Solved in c9cedd1: k_ges was replaced by E*A

2021-07-01 04:55 UTC, PhiSpel commented on content/11_pde/01_modellierung_einer_highline_dynamisch_pde.ipynb
> -    "$$\\frac{\\partial^2 z}{\\partial x^2} \\approx \\frac{z(x-h)-2z(x)+z(x+h)}{h^2} \\to \\frac{\\partial^2 z_i}{\\partial x^2} = \\frac{z_{i-1}-2z_i+z_{i+1}}{dx^2}.$$\n",
This will be explained in #23

2021-07-05 11:30 UTC, PhiSpel commented
- [ ] include Sandro's input from Prof. Groß and Bruch

2021-07-22 15:28 UTC, sandro-elsweijer requested changes
Lgtm, especially the inclusion of our references

2021-07-22 15:28 UTC, sandro-elsweijer commented on content/07_num_ode/03_modellierung_einer_highline_dynamisch.ipynb
> +    "Reale Slacklines haben eine Dehung von etwa 15 % bei 15 kN und ein Gewicht von etwa 60 g/m (siehe [hier](https://www.slacklineverband.com/know-how/slackline-vergleich-dehnung/) und [hier](https:
units

2021-07-22 21:07 UTC, PhiSpel commented on content/07_num_ode/03_modellierung_einer_highline_dynamisch.ipynb
> +    "Reale Slacklines haben eine Dehung von etwa 15 % bei 15 kN und ein Gewicht von etwa 60 g/m (siehe [hier](https://www.slacklineverband.com/know-how/slackline-vergleich-dehnung/) und [hier](https:
I assume you refer to the format? See 16f00c8

2021-07-24 14:56 UTC, sandro-elsweijer approved these changes

2021-07-24 14:56 UTC, merged