Phil spel motivation
joergbrech/Modellbildung-und-Simulation pull request #145
Opened 2021-06-24 06:37 UTC by PhiSpel

First contribution to the motivational chapter.

- NaSchr is kept in the exercises
- PDE model by Gerd is only shown

2021-06-24 14:31 UTC, PhiSpel commented
- [ ] Should we include the Traffic-PDE in the PDE chapter? Like this, we can have two examples throughout the book, Highline and Traffic

2021-07-13 16:18 UTC, sandro-elsweijer requested changes
This chapter looks great! My number of comments looks high, but it's mainly typesetting corrections

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "2. $a=30 m/s^2$"
Typesetting and units

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Also wird bei $71 km/h$ der maximale Fahrzeugdurchsatz $F(v = 71 km/h) = 2461 \\frac{\\text{Fahrzeuge}}{h}$ erreicht. "
units

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Also wird bei $71 km/h$ der maximale Fahrzeugdurchsatz $F(v = 71 km/h) = 2461 \\frac{\\text{Fahrzeuge}}{h}$ erreicht. "
And we should also add an admonition about that this would be the perfect velocity, if every driver would behave exactly right. But in reality the safety distance is at best guessed by the driver and at worst he/she does not even care about the safety distance.

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} Ausblick\n",
To comply with the contribution guideline, we could change this to a new section

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} Ausblick\n",
Or we push this into the next page, so that the next page is not only about finite volumes, but also mentions the Nagel Schreckenberg model

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/01_motivationPDE.ipynb
> +    "Im letzten Kapitel dieses Übungsbuches werden wir lernen, partielle Differentialgleichungen (PDEs) zu lösen. Damit können wir auch unser Verkehrsmodell wesentlich realistischer lösen und verschi
No comma here

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/01_motivationPDE.ipynb
> +      "nt = 180\n"
You should remove the output as well if you hide your cell

2021-07-13 16:18 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/01_motivationPDE.ipynb
> +      "nt = 180\n"
Also, you embedded the code two times in this page, but both times in hidden cells. It would be better to only embed the code once in the hidden cell and then tell the audience to unfold the hidden cell

2021-07-13 17:06 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "1. Lege die Fahrzeuglänge $L$ als Konstante fest, z.B. $L=4.5 m$.\n",
I usually do `$L = 4.5 \text{ m}$` with the spacing within the text box. This worked fine so far, but thank you for the idea of spacing with `\,`, that will surely come in handy in the future.

2021-07-13 17:25 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "- \"Tacho-Halbe-Regel\" $s = s(v) = \\frac{v}{2}$\n",
Good point. I would rather add the units behind, as they do not have a set place in the equations:

`$s(v) = \frac{v}{10} \cdot \frac{v}{10} \cdot\left[\frac{\text{s}^2}{\text{m}}\right] = \frac{v^2}{100} \cdot\left[\frac{\text{s}^2}{\text{m}}\right]$`
and
`$s = s(v) = \frac{v}{2}\cdot[\text{s}]$`

> Also, why are there so many sole `\` in your formulas?

I don't know, which do you mean?

2021-07-13 17:37 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Bevor wir die Ergebnisse an das Schweizer Verkehrsministerium übergeben, müssen wir zuletzt noch fragen: **Als wie realistisch schätzen wir diese Lösung ein?**\n",
Tell Dirk that :)

2021-07-13 17:53 UTC, PhiSpel commented on content/00_einleitung/01_motivation/01_motivationPDE.ipynb
> +    "Im letzten Kapitel dieses Übungsbuches werden wir lernen, partielle Differentialgleichungen (PDEs) zu lösen. Damit können wir auch unser Verkehrsmodell wesentlich realistischer lösen und verschi
I think yes, see [here](https://www.duden.de/sprachwissen/sprachratgeber/Das-Komma-beim-Infinitiv-mit-%E2%80%9Ezu%E2%80%9C)

2021-07-13 17:56 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} Ausblick\n",
see 158a996

2021-07-13 17:57 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Also wird bei $71 km/h$ der maximale Fahrzeugdurchsatz $F(v = 71 km/h) = 2461 \\frac{\\text{Fahrzeuge}}{h}$ erreicht. "
see 158a996

2021-07-13 17:57 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "2. $a=30 m/s^2$"
see 158a996

2021-07-13 17:57 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "$$s = s(v,a_{selbst},a_{VF},t_R)=\\frac{v}{3.6}\\cdot t_R + \\frac{\\left(\\frac{v}{3.6}\\right)^2}{2\\cdot a_{selbst}} - \\frac{\\left(\\frac{v}{3.6}\\right)^2}{2\\cdot a_{VF}}$$\n",
see 158a996

2021-07-13 17:57 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Bisher wird beim Sicherheitsabstand so getan, als ob im Bremsfall der Vorfahrende instantan von $v$ auf $0$ stoppt. Dessen Bremsweg $s_{VF} = \\frac{v^2}{2a_{VF}}$ wird in der Fahrpraxis oft vom
see 158a996

2021-07-13 17:57 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Wenn man beides berücksichtigt, ergibt sich mit Hilfe der Reaktionszeit $t_R$ und der Verzögerung $a$ als neuer Sicherheitsabstand $s$ ($v$ muss in unserem Fall von $km/h$ auf $m/s$ umgerechnet
see 158a996

2021-07-13 17:57 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    ":align: center\n",
see 158a996

2021-07-13 17:58 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "2. $\\lim_{v\\to\\infty}{F(v)}=\\lim_{v\\to\\infty}{\\frac{1000v}{4.5 + \\frac{v}{2}}} \\to 2000 \\frac{\\text{Fahrzeuge}}{h}$"
see 158a996

2021-07-13 17:58 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Damit erhalten wir die **Lösung**: Bei $v=21.21 \\frac{km}{h}$ wird ein maximaler Fahrzeugdurchsatz von $F(21.21 km/h) = 2357 \\frac{\\text{Fahrzeuge}}{h}$ erreicht."
see 158a996

2021-07-13 17:58 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Dies entspricht dem **fünften Schritt** im Lösungsschema: \"Gültigkeits und Randstellen Prüfung\"\n",
see 158a996

2021-07-13 17:58 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} MERKE\n",
see 158a996

2021-07-13 17:58 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "F = @(V) -(1000*V)./(4.5 + (V.^2)/100); % set F as negative to be able to use minimise function\n",
see 158a996

2021-07-13 17:58 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} MERKE\n",
see 158a996

2021-07-13 17:58 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "#### Einschub: Definition und Sätze zu Extremwerten\n",
see 158a996

2021-07-13 17:59 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} MERKE\n",
see 158a996

2021-07-13 17:59 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "1. Lege die Fahrzeuglänge $L$ als Konstante fest, z.B. $L=4.5 m$.\n",
see 158a996

2021-07-13 17:59 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} MERKE\n",
see 158a996

2021-07-13 17:59 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "$$F = F(v,s,L) = \\frac{1000 v}{L+s}, F>0$$\n",
see 158a996

2021-07-13 17:59 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "3. Länge $L$\n",
see 158a996

2021-07-13 18:00 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{image} images/trafficvariables.png\n",
see 158a996

2021-07-13 18:00 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "***Bei welcher Geschwindigkeit ist der Verkehrsfluss F [Fzg./h]' d.h. die Anzahl der passierenden Fahrzeuge pro Stunde, am größten?***\n",
see 158a996

2021-07-13 18:00 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{admonition} MERKE\n",
see 158a996

2021-07-13 18:00 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{image} images/tunnel-pixabay.jpg\n",
see 158a996

2021-07-13 22:08 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{image} images/lowv_lows.png\n",
It's from Dirk's lecture, so it's fine

2021-07-13 22:08 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{image} images/highv_highs.png\n",
It's from Dirk's lecture, so it's fine

2021-07-13 22:08 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "```{image} images/trafficvariables.png\n",
It's from Dirk's lecture, so it's fine

2021-07-14 05:32 UTC, PhiSpel commented on content/00_einleitung/01_motivation/01_motivationPDE.ipynb
> +      "nt = 180\n"
see 281888e

2021-07-22 15:36 UTC, sandro-elsweijer requested changes
Nearly perfect

2021-07-22 15:36 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Diese Regeln sind einheitenlos,e aher rechnen wir einheitenlos so weiter, dass $F$ die Einheit $\\left[\\frac{\\text{Fahrzeuge}}{\\text{h}}\\right]$ erhält. Mithilfe der \"Bremsweg-Regel\" und d
Typo

2021-07-22 15:36 UTC, sandro-elsweijer commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "$$\n",
I would exclude the units for the whole calculation

2021-07-22 21:13 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "$$\n",
I kept the units in the last line, this made more sense to me, see 0889096

2021-07-22 21:13 UTC, PhiSpel commented on content/00_einleitung/01_motivation/00_motivation.ipynb
> +    "Diese Regeln sind einheitenlos,e aher rechnen wir einheitenlos so weiter, dass $F$ die Einheit $\\left[\\frac{\\text{Fahrzeuge}}{\\text{h}}\\right]$ erhält. Mithilfe der \"Bremsweg-Regel\" und d
See 0889096

2021-07-24 14:54 UTC, sandro-elsweijer approved these changes

2021-07-24 14:55 UTC, merged