Phil spel num diff
joergbrech/Modellbildung-und-Simulation pull request #147
Opened 2021-07-05 14:09 UTC by PhiSpel

created an exercise about difference quotients

pull after #46

closes #146

2021-08-04 12:18 UTC, sandro-elsweijer reviewed
Only minor things need to be done

2021-08-04 12:18 UTC, sandro-elsweijer commented on content/06_Differentiation_Integration/02_integration_and_stepcontrol.ipynb
> +    "Den Quellcode des `unit tests` können Sie hier ausklappen. Sehen Sie sich [](content:references:unit_testing_intro) an, um Ihre Erinnerung über Unit Tests aufzufrischen.\n",
Grammar

2021-08-16 16:47 UTC, PhiSpel commented on content/06_Differentiation_Integration/02_integration_and_stepcontrol.ipynb
> +    "Den Quellcode des `unit tests` können Sie hier ausklappen. Sehen Sie sich [](content:references:unit_testing_intro) an, um Ihre Erinnerung über Unit Tests aufzufrischen.\n",
see d5197fb

2021-08-16 16:47 UTC, PhiSpel commented on content/06_Differentiation_Integration/01_differentiation.ipynb
> +    "Bei sehr komplexen Funktionen ist die Verringerung von Funktionsauswertungen entscheident für die Performanz Ihres Programms.\n",
see d5197fb

2021-08-16 16:48 UTC, PhiSpel commented on content/06_Differentiation_Integration/01_differentiation.ipynb
> +    "%%file numDiff2.m\n",
see d5197fb

2021-08-16 16:48 UTC, PhiSpel commented on content/06_Differentiation_Integration/01_differentiation.ipynb
> +    "%%file numDiff.m\n",
Good point. I removed the keyword so the code will be executed directly. Creating a file is not necessary.
see d5197fb

2021-08-16 16:48 UTC, PhiSpel commented on content/06_Differentiation_Integration/01_differentiation.ipynb
> +    "Differenzenquotienten können für beliebig hohe Ableitungen gebildet werden. Der Fehler wird mit geringerer Schrittweite $dx$ kleiner. Wie stark der Fehler kleiner wird, beschreibt die Fehlerordn
see d5197fb

2021-08-18 13:02 UTC, sandro-elsweijer requested changes

2021-09-02 10:47 UTC, sandro-elsweijer approved these changes

2021-09-02 10:48 UTC, merged