reordered PDE chapters & added a plot for u(rho) vs rho
joergbrech/Modellbildung-und-Simulation pull request #162
Opened 2021-07-26 07:11 UTC by PhiSpel

closes #161

2021-08-04 12:25 UTC, sandro-elsweijer commented on content/11_pde/02_trafficPDE.ipynb
> +    "drawnow"
Could you add some context to the plot?

2021-08-04 12:25 UTC, sandro-elsweijer requested changes

2021-08-04 12:25 UTC, sandro-elsweijer commented on content/11_pde/02_trafficPDE.ipynb
> +   ]
Could you add some context to the plot?

2021-08-16 17:01 UTC, PhiSpel commented on content/11_pde/02_trafficPDE.ipynb
> +   ]
see 086daab, does this work for you?

2021-08-18 13:09 UTC, sandro-elsweijer approved these changes

2021-08-18 13:09 UTC, merged