Phil spel/exp imp solver demonstrator
joergbrech/Modellbildung-und-Simulation pull request #163
Opened 2021-07-28 14:30 UTC by PhiSpel

checklist in issue!

closes #148

2021-08-04 14:13 UTC, sandro-elsweijer requested changes

2021-08-16 17:37 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "Das liegt vor allem an der hohen Lipschitzkonstante, die für explizite Verfahren eine sehr kleine Schrittweite bedeutet $\\left(h<\\frac{2}{|\\lambda|}\\right)$."
Added a little bit more context and explained that h_max is easily determined for e^\lambda*t
See dfe386a

2021-08-16 17:37 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "- Bei welchen Funktionen ist das explizite Verfahren nicht mehr hilfreich? Was macht die'Steifheit' dieser Funktionen qualitativ aus?\n",
See dfe386a

2021-08-18 13:17 UTC, sandro-elsweijer commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "Das liegt vor allem an der hohen Lipschitzkonstante, die für explizite Verfahren eine sehr kleine Schrittweite bedeutet $\\left(h<\\frac{2}{|\\lambda|}\\right)$."
The part after "Mathematisch ausgedrückt:" seems weird, maybe we should give the formula its own line and refine the grammar a little.

2021-08-18 15:12 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "Das liegt vor allem an der hohen Lipschitzkonstante, die für explizite Verfahren eine sehr kleine Schrittweite bedeutet $\\left(h<\\frac{2}{|\\lambda|}\\right)$."
see ba54f47

2021-09-02 10:46 UTC, merged