241 ps/expimpsolver improvements
joergbrech/Modellbildung-und-Simulation pull request #246
Opened 2022-02-03 16:12 UTC by PhiSpel

# Description

Gerd had some comments about the Explicit/Implicit comparison demonstrator.
Closes #241 

## Checklist

 - [x] This pull request is associated to an issue
 - [x] All used resources use a CC-by-SA license or less and are marked appropriately, see [our contribution guide](CONTRIBUTING.md).
 - [x] All used resources have been added to the list in `[TODO, does not exist yet]`
 - [x] New exercises include learning requirements and learning goals.

2022-03-04 13:48 UTC, m-r-schenk requested changes

2022-03-04 13:48 UTC, m-r-schenk commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "$$\\lambda \\ge \\left|\\frac{f(t,y_1)-f(t,y_2)|}{y_1-y_2}\\right| \\,\\forall\\, y_1,y_2 \\in \\mathbb{D}$$\n",
I learned, that the universal quantifier comes first, before the equation.

2022-03-04 13:48 UTC, m-r-schenk commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "Entscheidend dafür, ob eine hohe maximale Steigung vorliegt. Diese wird mit der Lipschitzkonstanten beschrieben, die eine obere Schranke der Steigung $f_y$ aufstellt (mit der ODE $y' = f(t,y)$):
This is not a proper sentence...

2022-03-04 13:48 UTC, m-r-schenk commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "$$\\forall y_1,y_2 \\in \\mathbb{D} \\left(\\lambda \\ge \\left|\\frac{f(t,y_1)-f(t,y_2)|}{y_1-y_2}\\right|\\right)$$\n",
I learned that the universal quantifier comes first, before the formula...

2022-03-05 11:00 UTC, LeaKruehler commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "Entscheidend dafür, ob eine hohe maximale Steigung vorliegt. Diese wird mit der Lipschitzkonstanten beschrieben, die eine obere Schranke der Steigung $f_y$ aufstellt (mit der ODE $y' = f(t,y)$):
I changed it to "Entscheidend dafür ist, ob eine hohe maximale Steigung vorliegt."

2022-03-05 11:01 UTC, LeaKruehler commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "$$\\forall y_1,y_2 \\in \\mathbb{D} \\left(\\lambda \\ge \\left|\\frac{f(t,y_1)-f(t,y_2)|}{y_1-y_2}\\right|\\right)$$\n",
I didn't change that, because I have no clue about what you mean.

2022-03-05 11:02 UTC, LeaKruehler commented
Is ready to be merged after Martins requested changes about the universal quantifier and formula have been made.

2022-03-05 12:24 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "Entscheidend dafür, ob eine hohe maximale Steigung vorliegt. Diese wird mit der Lipschitzkonstanten beschrieben, die eine obere Schranke der Steigung $f_y$ aufstellt (mit der ODE $y' = f(t,y)$):
This works, sorry, I think I just forgot the "ist"

2022-03-05 12:29 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "$$\\forall y_1,y_2 \\in \\mathbb{D} \\left(\\lambda \\ge \\left|\\frac{f(t,y_1)-f(t,y_2)|}{y_1-y_2}\\right|\\right)$$\n",
I have no opinion about this, I just know it from differentiating between cases, i.e. $|x|=\left{\begin{array} x & \forall x \ge 0 \\ -x & \forall x < 0 \right$

2022-03-05 12:35 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "**Matlab Code**"
Mathworks spells MATLAB in all-caps. I agree on unifying this, we can just briefly agree on which spelling to use in the next meeting

2022-03-09 17:04 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "**Matlab Code**"
Will be spelled `Matlab`

2022-03-09 17:04 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "$$\\forall y_1,y_2 \\in \\mathbb{D} \\left(\\lambda \\ge \\left|\\frac{f(t,y_1)-f(t,y_2)|}{y_1-y_2}\\right|\\right)$$\n",
Works like this

2022-03-09 17:05 UTC, PhiSpel commented on content/07_num_ode/02_stabilitaet_eulerverfahren.ipynb
> +    "$$\\lambda \\ge \\left|\\frac{f(t,y_1)-f(t,y_2)|}{y_1-y_2}\\right| \\,\\forall\\, y_1,y_2 \\in \\mathbb{D}$$\n",
ok

2022-03-23 15:08 UTC, PhiSpel commented
depends on #206

2022-03-24 12:26 UTC, m-r-schenk approved these changes

2022-03-24 12:26 UTC, merged